### ISSUE TITLE
mount.nfs: an incorrect mount option was specified

### ISSUE THREAD

**Issue by igordcard** [alvistack/vagrant-kubernetes#1]
Using libvirt provider and vagrant 2.2.14.

```
==> default: Pruning invalid NFS exports. Administrator privileges will be required...
==> default: Removing domain...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.121.1:/root/vagrant/k23-1 /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: an incorrect mount option was specified
```

Unless I specifically disable UDP for NFS (without changing version to 4), the above is what I get.

This fixes it for me:
```
  config.vm.synced_folder ".", "/vagrant",
    type: "nfs",
    nfs_udp: false
```

**Comment by hswong3i** [comment]
Related to recent nfs-utils now disable NFS via UDP by default, see https://github.com/hashicorp/vagrant/issues/9361#issuecomment-367881711

**Comment by hswong3i** [comment]
Moreover, I recommend to use VirtIO if possible, much faster and stable, see https://github.com/alvistack/ansible-collection-kubernetes/blob/master/molecule/ubuntu-20.04/molecule.yml#L31

**Comment by RafaelMoreira1180778** [comment]
@hswong3i How may we specifically use VirtIO? (Arch Linux)

I am using the default `Vagrantfile` with the libvirt provider.

**Comment by hswong3i** [comment]
@RafaelMoreira1180778 something like this: https://github.com/alvistack/ansible-role-gitlab_runner/blob/master/templates/opt/gitlab-runner/executors/vagrant/config.sh.j2#L46-L68
